CREATE TABLE [bins] (
	bin_id TEXT NOT NULL PRIMARY KEY,
	created_at DATETIME NOT NULL,
	owner TEXT
);
CREATE TABLE [requests] (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	timestamp DATETIME NOT NULL,
	headers TEXT NOT NULL,
	body TEXT NOT NULL,
	host TEXT NOT NULL,
	"method" TEXT NOT NULL,
	bin text NOT NULL,
	FOREIGN KEY (bin) REFERENCES bins(bin_id)	
);
