name: Build and Unit Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go:1.23
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -v ./cmd/main.go
      - name: Test with the Go CLI
        run: go test ./...
